<?php
$z[0]=Array("global","",728,760);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",992,1024);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1075,1107);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1255,1282);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("channel","\r\n      	<li><a href='[field:typelink/]'  rel='dropmenu2'><span>[field:typename/]</span></a></li>\r\n      	",1327,1473);
$z[4][4]['type']="top";

?>