<?php
$z[0]=Array("field","",149,178);
$z[0][4]['name']="typename";
$z[1]=Array("field","",206,234);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","			\r\n<div id=\"case\">\r\n    <div class=\"case_pic\"><a href=\"[field:arcurl/]\" target=\"_blank\" style=\"height:113px; overflow:hidden;\">\r\n      <img src=\"[field:picname/]\" width=\"160\" height=\"120\" style=\"border:0px solid #CCCCCC;\" />\r\n    </a></div>\r\n    <div class=\"case_tit\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></div>\r\n</div>\r\n",342,747);
$z[2][4]['row']="8";

?>