<?php
$z[0]=Array("global","",320,352);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",424,459);
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",544,576);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",853,885);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",2055,2096);
$z[4][4]['filename']="right_anli.htm";
$z[5]=Array("include","",2144,2181);
$z[5][4]['filename']="footer.htm";

?>