<?php
$z[0]=Array("global","",312,344);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",418,453);
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",538,570);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",629,648);
$z[3][4]['name']="title";
$z[4]=Array("field","",668,724);
$z[4][4]['name']="pubdate";
$z[4][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[5]=Array("field","",736,754);
$z[5][4]['name']="body";
$z[6]=Array("field","",780,807);
$z[6][4]['name']="phpurl";
$z[7]=Array("field","",831,854);
$z[7][4]['name']="id";
$z[8]=Array("field","",859,883);
$z[8][4]['name']="mid";
$z[9]=Array("include","",994,1030);
$z[9][4]['filename']="right.htm";
$z[10]=Array("incoude","",1070,1107);
$z[10][4]['filename']="footer.htm";

?>