<?php
$z[0]=Array("global","",73,100);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",112,144);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",167,193);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",257,284);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",314,341);
$z[4][4]['name']="cfg_indexurl";
$z[5]=Array("global","",377,404);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",635,662);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("channel","\r\n<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n",714,950);
$z[7][4]['type']="top";
$z[7][4]['row']="7";
$z[7][4]['currentstyle']="<li class='center'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[8]=Array("type","\r\n<img src=\"../../templets/moban/images/banner[field:id/].jpg\" width=\"980\" height=\"175\" alt=\"[field:typename/]\" />\r\n",997,1136);

?>