<?php
$z[0]=Array("global","",461,493);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",565,600);
$z[1][4]['filename']="head.htm";
$z[2]=Array("type","\r\n<h2>[field:typename/]</h2>\r\n",816,869);
$z[3]=Array("list","	\r\n<li><b>2014-05-29</b><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",905,1018);
$z[3][4]['pagesize']="10";
$z[4]=Array("pagelist","",1122,1200);
$z[4][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[4][4]['listsize']="1";
$z[5]=Array("include","",1265,1306);
$z[5][4]['filename']="right_news.htm";
$z[6]=Array("include","",1348,1385);
$z[6][4]['filename']="footer.htm";

?>