<?php
$z[0]=Array("global","",677,709);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("include","",781,816);
$z[1][4]['filename']="head.htm";
$z[2]=Array("list","              \r\n<div id=\"case\">\r\n  <div class=\"case_pic\">\r\n      <a href=\"[field:arcurl/]\" target=\"_blank\" style=\"height:113px; overflow:hidden;\"><img src=\"[field:picname/]\" width=\"160\" height=\"120\" style=\"border:0px solid #CCCCCC;\" /></a>\r\n  </div>\r\n\r\n  <div class=\"case_tit\">\r\n      <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\r\n  </div>\r\n</div>\r\n",1293,1696);
$z[2][4]['pagesize']="16";
$z[3]=Array("pagelist","",1761,1838);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="1";
$z[4]=Array("include","",2058,2094);
$z[4][4]['filename']="right.htm";
$z[5]=Array("include","",2126,2163);
$z[5][4]['filename']="footer.htm";

?>