<?php
$z[0]=Array("type","\r\n<img src=\"../../templets/moban/images/right[field:id/].jpg\" style=\"padding-bottom:10px;\" alt=\"[field:typename/]\" />\r\n",20,162);
$z[1]=Array("channelartlist","\r\n<li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n",200,357);
$z[1][4]['row']="4";
$z[1][4]['typeid']="9,10,11,12";
$z[2]=Array("global","",443,475);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n",631,816);
$z[3][4]['row']="6";
$z[3][4]['titlelen']="30";
$z[3][4]['orderby']="pubdate";
$z[3][4]['typeid']="8";

?>