<?php
$z[0]=Array("type","\r\n<img src=\"../../templets/moban/images/right[field:id/].jpg\" style=\"padding-bottom:10px;\" alt=\"[field:typename/]\" />\r\n",20,162);
$z[1]=Array("global","",271,303);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n",459,644);
$z[2][4]['row']="6";
$z[2][4]['titlelen']="30";
$z[2][4]['orderby']="pubdate";
$z[2][4]['typeid']="8";

?>